import type { Metadata } from 'next';
import { AnimatedSection } from '@/components/marketing/AnimatedSection';
import { FileText } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service — JobHunter',
  description: 'Terms of service for the JobHunter Chrome extension and web dashboard.',
};

export default function TermsPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative pt-32 pb-12 overflow-hidden">
        <div className="absolute inset-0 bg-slate-950" />
        <div className="absolute inset-0 dot-grid opacity-30" />
        <div className="relative z-10 max-w-3xl mx-auto px-6">
          <AnimatedSection>
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-sm font-medium mb-6">
              <FileText className="w-3.5 h-3.5" />
              Last updated: February 2026
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold tracking-tight mb-4">
              Terms of Service
            </h1>
            <p className="text-slate-400 text-lg">
              By using JobHunter, you agree to the following terms.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/* Content */}
      <section className="relative pb-28">
        <div className="max-w-3xl mx-auto px-6">
          <div className="space-y-10">
            <TermsSection title="1. Acceptance of Terms">
              <p>
                By installing the JobHunter Chrome extension or using the
                JobHunter web dashboard, you agree to these Terms of Service.
                If you do not agree, please do not use the service.
              </p>
            </TermsSection>

            <TermsSection title="2. Description of Service">
              <p>
                JobHunter is a free, open-source tool that helps automate job
                application form filling using AI-generated answers and profile
                data shortcuts. The service includes a Chrome browser extension
                and a web dashboard.
              </p>
            </TermsSection>

            <TermsSection title="3. User Responsibilities">
              <ul>
                <li>
                  <strong>Accuracy:</strong> You are responsible for the
                  accuracy of information in your profile and the answers
                  submitted in job applications. Always review AI-generated
                  content before submitting.
                </li>
                <li>
                  <strong>API Keys:</strong> You are responsible for securing
                  your AI provider API keys and any costs incurred from their
                  usage.
                </li>
                <li>
                  <strong>Compliance:</strong> You agree to use JobHunter in
                  compliance with the terms of service of the job platforms you
                  apply on.
                </li>
                <li>
                  <strong>Account Security:</strong> You are responsible for
                  maintaining the security of your account credentials.
                </li>
              </ul>
            </TermsSection>

            <TermsSection title="4. AI-Generated Content">
              <p>
                Answers generated by JobHunter&apos;s AI feature are suggestions
                only. They should be reviewed, edited, and personalized before
                submission. We make no guarantees about the accuracy, quality,
                or suitability of AI-generated content. You are solely
                responsible for any content you submit in job applications.
              </p>
            </TermsSection>

            <TermsSection title="5. Free Service">
              <p>
                JobHunter is provided free of charge. We do not guarantee
                uptime, availability, or uninterrupted service. The service
                may be modified, suspended, or discontinued at any time.
              </p>
            </TermsSection>

            <TermsSection title="6. Intellectual Property">
              <p>
                JobHunter is open-source software. The source code is available
                under its respective license on GitHub. You may use, modify,
                and distribute the software in accordance with the license
                terms.
              </p>
            </TermsSection>

            <TermsSection title="7. Limitation of Liability">
              <p>
                JobHunter is provided &quot;as is&quot; without warranty of any kind.
                To the fullest extent permitted by law, we shall not be liable
                for any damages arising from the use of this service,
                including but not limited to:
              </p>
              <ul>
                <li>Inaccurate or inappropriate AI-generated answers</li>
                <li>Failed or missed job applications</li>
                <li>API costs from third-party AI providers</li>
                <li>Data loss or security breaches</li>
                <li>Service interruptions or downtime</li>
              </ul>
            </TermsSection>

            <TermsSection title="8. Third-Party Services">
              <p>
                JobHunter integrates with third-party AI providers (OpenAI,
                Anthropic, OpenRouter) and operates on third-party job
                platforms. We are not responsible for the policies, practices,
                or availability of these third-party services.
              </p>
            </TermsSection>

            <TermsSection title="9. Modifications">
              <p>
                We reserve the right to modify these terms at any time.
                Continued use of JobHunter after changes constitutes acceptance
                of the updated terms.
              </p>
            </TermsSection>

            <TermsSection title="10. Termination">
              <p>
                You may stop using JobHunter at any time by uninstalling the
                extension and deleting your account. We reserve the right to
                terminate accounts that violate these terms.
              </p>
            </TermsSection>

            <TermsSection title="11. Contact">
              <p>
                For questions about these terms, please open an issue on our
                GitHub repository.
              </p>
            </TermsSection>
          </div>
        </div>
      </section>
    </>
  );
}

function TermsSection({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <AnimatedSection>
      <div>
        <h2 className="text-xl font-bold text-white mb-4">{title}</h2>
        <div className="text-slate-400 text-sm leading-relaxed space-y-3 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-2 [&_strong]:text-slate-200">
          {children}
        </div>
      </div>
    </AnimatedSection>
  );
}
